[project]
name = "atcoder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "y-chiba1008", email = "118287721+y-chiba1008@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
atcoder = "atcoder:main"

[build-system]
requires = ["uv_build>=0.11.8,<0.12.0"]
build-backend = "uv_build"
